settings:
  application:
    enabledp: false
    host: 0.0.0.0
    mode: dev
    name: testApp
    port: 8000
    readtimeout: 1
    writertimeout: 2
  database:
    driver: mysql
    source: root:123456@tcp(127.0.0.1:3306)/school_bus?charset=utf8&parseTime=True&loc=Local&timeout=3000ms
  gen:
    dbname: school_bus
    frontpath: ../go-admin-ui/src
  jwt:
    secret: go-admin
    timeout: 3600
  logger:
    enabledbus: true
    enableddb: false
    enabledreq: false
    level: all
    path: temp/logs
    stdout: true
  redis:
    RedisConn: 127.0.0.1:6379
    RedisDbNum: 0
    RedisPassword: ""
    RedisMaxIdle: 5
    RedisMaxActive: 20
